"""
Seed Data for Urban Traffic Hazards in Vietnam (TP. Hồ Chí Minh & Hà Nội).
Realistic coordinates for speed cameras, flood points, speed limit zones.
"""
from typing import List
from backend.src.domain.hazard import Hazard, HazardType, Severity

DEFAULT_HAZARDS: List[Hazard] = [
    # --- TP. HỒ CHÍ MINH ---
    Hazard(
        id="hcm-cam-01",
        type=HazardType.SPEED_CAMERA,
        title="Camera Phạt Nguội Ngã tư Hàng Xanh",
        description="Camera AI giám sát vượt đèn đỏ, lấn làn xe máy và tốc độ trên 50 km/h.",
        latitude=10.8018,
        longitude=106.7115,
        radius_meters=250.0,
        severity=Severity.DANGER,
        speed_limit=50,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-cam-02",
        type=HazardType.SPEED_CAMERA,
        title="Camera Tốc Độ Cầu Sài Gòn",
        description="Đoạn đường dẫn lên Cầu Sài Gòn hướng về TP. Thủ Đức, giám sát tốc độ tối đa 50 km/h.",
        latitude=10.7997,
        longitude=106.7214,
        radius_meters=300.0,
        severity=Severity.DANGER,
        speed_limit=50,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-cam-03",
        type=HazardType.SPEED_CAMERA,
        title="Camera Giao lộ Mai Chí Thọ - Đồng Văn Cống",
        description="Giám sát lỗi rẽ sai làn xe máy và vượt đèn đỏ hướng hầm Thủ Thiêm.",
        latitude=10.7812,
        longitude=106.7489,
        radius_meters=200.0,
        severity=Severity.DANGER,
        speed_limit=60,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-flood-01",
        type=HazardType.FLOOD_POINT,
        title="Điểm Ngập Nước Đường Nguyễn Hữu Cảnh",
        description="Đoạn chân cầu vượt Nguyễn Hữu Cảnh thường xuyên ngập sâu 30-50cm khi triều cường hoặc mưa lớn.",
        latitude=10.7935,
        longitude=106.7188,
        radius_meters=350.0,
        severity=Severity.WARNING,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-flood-02",
        type=HazardType.FLOOD_POINT,
        title="Điểm Ngập Nước Đường Huỳnh Tấn Phát (Quận 7)",
        description="Ngập sâu đoạn giao với đường Trần Xuân Soạn khi có triều cường đạt đỉnh.",
        latitude=10.7523,
        longitude=106.7312,
        radius_meters=400.0,
        severity=Severity.WARNING,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-flood-03",
        type=HazardType.FLOOD_POINT,
        title="Điểm Ngập Nước Đường Quốc Hương (Thảo Điền)",
        description="Khu vực Thảo Điền ngập nước mùa mưa, xe máy dễ chết máy.",
        latitude=10.8045,
        longitude=106.7335,
        radius_meters=300.0,
        severity=Severity.WARNING,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-speed-01",
        type=HazardType.SPEED_LIMIT,
        title="Giới Hạn Tốc Độ Đại Lộ Võ Văn Kiệt",
        description="Làn xe máy trong đô thị giới hạn tối đa 50 km/h, có lực lượng CSGT tuần tra.",
        latitude=10.7635,
        longitude=106.6902,
        radius_meters=300.0,
        severity=Severity.INFO,
        speed_limit=50,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-speed-02",
        type=HazardType.SPEED_LIMIT,
        title="Đoạn Giới Hạn Tốc Độ Đường Phạm Văn Đồng",
        description="Làn hỗn hợp xe máy tối đa 50 km/h, cấm rẽ đột ngột vào làn ô tô.",
        latitude=10.8241,
        longitude=106.6998,
        radius_meters=250.0,
        severity=Severity.INFO,
        speed_limit=50,
        is_active=True,
        city="Ho_Chi_Minh",
    ),
    Hazard(
        id="hcm-jam-01",
        type=HazardType.TRAFFIC_JAM,
        title="Điểm Ùn Tắc Vòng Xoay Dân Chủ",
        description="Mật độ phương tiện cực cao giờ cao điểm sáng và chiều, khuyến cáo rẽ hướng Cách Mạng Tháng 8.",
        latitude=10.7788,
        longitude=106.6821,
        radius_meters=250.0,
        severity=Severity.WARNING,
        is_active=True,
        city="Ho_Chi_Minh",
    ),

    # --- HÀ NỘI ---
    Hazard(
        id="hn-cam-01",
        type=HazardType.SPEED_CAMERA,
        title="Camera Phạt Nguội Ngã tư Đại Cồ Việt - Giải Phóng",
        description="Camera tự động quét vượt đèn đỏ và dừng đè vạch người đi bộ.",
        latitude=21.0068,
        longitude=105.8427,
        radius_meters=250.0,
        severity=Severity.DANGER,
        speed_limit=50,
        is_active=True,
        city="Ha_Noi",
    ),
    Hazard(
        id="hn-flood-01",
        type=HazardType.FLOOD_POINT,
        title="Điểm Ngập Úng Phố Hoa Bằng (Cầu Giấy)",
        description="Điểm ngập úng trũng sâu của Hà Nội khi có mưa rào lớn.",
        latitude=21.0264,
        longitude=105.7946,
        radius_meters=300.0,
        severity=Severity.WARNING,
        is_active=True,
        city="Ha_Noi",
    ),
]
